packages:
    - .
onlyBuiltDependencies:
    - "@prisma/engines"
    - esbuild
    - prisma
ignoredBuiltDependencies:
    - sharp
    - unrs-resolver
allowBuilds:
    "@prisma/engines": true
    "@sentry/cli": true
    esbuild: true
    prisma: true
    sharp: true
    unrs-resolver: true
